name: Archive and Release

on:
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: zip -r system.zip .

      - name: Upload ZIP archive
        uses: actions/upload-artifact@v4
        with:
          name: system-zip
          path: system.zip

      - name: Upload system.json
        uses: actions/upload-artifact@v4
        with:
          name: system-json
          path: system.json

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete existing release
        run: |
          gh release delete release -y || true
          gh api -X DELETE repos/${{ github.repository }}/git/refs/tags/release || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        run: git tag release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new tag
        run: git push origin release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download ZIP archive
        uses: actions/download-artifact@v4
        with:
          name: system-zip

      - name: Download system.json
        uses: actions/download-artifact@v4
        with:
          name: system-json

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: release
          name: release
          body: Latest release
          artifacts: |
            system.zip
            system.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
